= TRUST Platform
:page-layout: default
:page-tags: framework, software, trust_platform
:page-illustration: fa-solid fa-cube
:description: TRUST Platform - TRUST is a High Performance Computing (HPC) thermohydraulic engine for Computational Fluid Dynamics (CFD). This software was originally designed for c...
:icons: font
:page-work-packages: WP3, WP7

[.lead]
TRUST is a High Performance Computing (HPC) thermohydraulic engine for Computational Fluid Dynamics (CFD). This software was originally designed for conduction, incompressible single-phase, and Low Mach Number (LMN) flows with a robust Weakly-Compressible (WC) multi-species solver. TRUST is also being progressively ported to support GPU acceleration (NVidia/AMD).

[.section-gray]
--
[discrete]
== Overview

[.grid.grid-2.gap-2]
====
____
icon:code-branch[size=2x,role=text-primary] *Repository*

https://github.com/cea-trust-platform
____

____
icon:file-contract[size=2x,role=text-success] *License*

OSS::BSD
____

____
icon:book[size=2x,role=text-info] *Documentation*

https://cea-trust-platform.readthedocs.io/en/latest/
____

____
icon:comments[size=2x,role=text-warning] *Discussion*

https://github.com/cea-trust-platform/trust-code/issues____
====
--

== Criteria Evaluation

=== Packaging

Software should be packaged (preferably using Spack or Guix package formats) and published in public repositories.

* [ ] Packages exist
* [ ] Available in Spack
* [ ] Available in Guix-HPC
* [ ] Docker image available
* [ ] Apptainer/Singularity available


=== Testing & CI/CD

Software should include validation tests triggered through automated mechanisms.

* [x] Unit tests exist
* [x] Continuous Integration configured
* [ ] CI runs on each release
* [ ] Benchmarking tests exist

=== Repository & Contributions

* [x] Public source repository available
* [x] Supports contributions via pull requests

Repository: https://github.com/cea-trust-platform

=== License

Sources should be published under a clearly-identified free software license.

* [x] License clearly stated
* [x] FLOSS license (FSF/OSI conformant)
* [ ] SPDX identifiers used
* [ ] REUSE compliant

* BSD

=== Documentation

* [x] Documentation exists
* [x] Easily browsable online

Documentation: https://cea-trust-platform.readthedocs.io/en/latest/

=== API Compatibility

* [x] API changes documented
* [ ] Semantic versioning used
* [x] Release policy defined

== Work Packages

This framework is involved in the following work packages:

=== WP3 icon:check-circle[role=text-success]
Topics: multiphysics coupling, krylov solver, direct solver
_Benchmarked in this WP_

=== WP7 icon:check-circle[role=text-success]
Topics: Energy, Physics
_Benchmarked in this WP_


== Technical Details

*Languages:* C++, Fortran, Python, C++14

*Parallelism:* MPI, GPU

*Data Formats:* HDF5, MED, VTK, in-house format

*Resilience:* Checkpoint restart

== Partners

*Lead Partner:* CEA

*Consortium:* CEA

