site:
  title: Exa-MA -- Methods and Algorithms for Exascale Computing
  url: https://numpex.github.io/exa-ma/
  start_page: ROOT::index.adoc
content:
  sources:
  - url: .
    branches: HEAD
    start_path: docs
ui:
  supplemental_files: ./docs/antora/supplemental-ui
  bundle:
    url: https://github.com/feelpp/antora-ui/releases/download/v0.52/ui-bundle.zip
    snapshot: true
output:
  clean: true
  dir: public
antora:
  extensions:
  - '@antora/collector-extension'
asciidoc:
  extensions:
  - 'asciidoctor-kroki'
  attributes:
    project_name: Exa-MA
    project_version: 2.0.2
    numbered: true
    allow-uri-read: true
    hide-uri-scheme: true
    feelpp: Feel++
    angiotk: AngioTK
    4fastsim: 4FastSim
    stem: latexmath
    hemotumpp: Hemotum++
    eye2brain: Eye2Brain
    swimmer: Swimmer
    :exama: Exa-MA
    :numpex: NumPEx
    kroki-fetch-diagram: true
    kroki-server-url: https://kroki.io
